### ISSUE TITLE
Vampire Datapack To Fix Compatibility maybe? 

### ISSUE THREAD

**Issue by Akane-N** [Fusion-Flux/Origins-Umbrellas#7]
Ok here is the vampire datapack, hopefully this helps ^~^ (hopefully this sends right, never done this before)

[Vampire.zip](https://github.com/Fusion-Flux/Origins-Umbrellas/files/8520720/Vampire.zip)

**Comment by KizuneOkami** [comment]
what's kinda weird it says that it's not compatible with other datapacks but this one works (attached file) and the other one (vampire) doesn't
it might be because of the code in the origin itself that they are different
[WanderingSoulV2.3.zip](https://github.com/Fusion-Flux/Origins-Umbrellas/files/8565904/WanderingSoulV2.3.zip)

**Comment by Akane-N** [comment]
That's very strange, I honestly wouldn't even know where to start to fix this, because I'm very new to this stuff, all I know is that it works on afterlife and this is the vampire datapack they use T.T I'm honestly very desperate at this point to get it working on my server but anytime I message on the origins discord for help they just get lost in the sea of messages, would you or anyone you know be willing to take a look and see if its possible to get it working? I absolutely hate asking cause I don't like bothering people, but as I said I'm honestly desperate at this point and don't know what to do sorry, (also sorry for my late response i was away for a bit)

**Comment by twixstix** [comment]
The reason the vampire datapack doesn't work is because it is coded incorrectly. It looks for a combination of "exposed to sky" and "is daytime", rather than "exposed to sun", which the umbrellas look for. This is a fixed version of the datapack that will work with umbrellas.
[vampire-fixed.zip](https://github.com/Fusion-Flux/Origins-Umbrellas/files/8945939/vampire-fixed.zip)

**Comment by Akane-N** [comment]
thankyou very much for this!! ^~^
